steps:
  # 1. Build the Docker image using the production Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/microservices-dev-505620/image-registry/oorders-ms',
        '-f',
        'dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]
  # 2. Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-east4-docker.pkg.dev/microservices-dev-505620/image-registry/orders-ms',
      ]

options:
  logging: CLOUD_LOGGING_ONLY
